### ISSUE TITLE
fix dead links

### ISSUE THREAD

**Issue by stacksmash76** [TritonDataCenter/smartos-docs#64]
On https://docs.smartos.org/lx-branded-zones/ the "VM" link is dead
On https://docs.smartos.org/managing-images/#viewing-downloading-public-images the imgadm(1m) link is dead (/1m/ needs to be stripped)

**Comment by danmcd** [comment]
VM link has a typo.  

This repo needs an update related to https://github.com/illumos/ipd/blob/master/ipd/0004/README.md.

Watch for a PR soon about these.
